### ISSUE TITLE
Auto changelog modifications when releasing

### ISSUE THREAD

**Issue by osrf-migration** [ignition-tooling/release-tools#10]
**Original report ([archived issue](https://osrf-migration.github.io/ignition-tooling-gh-pages/#!/osrf/release-tools/issues/10)) by Jose Luis Rivero (Bitbucket: [Jose Luis Rivero](https://bitbucket.org/%7Bd12309b2-f745-42ee-b119-aec4fcdf81fe%7D/)).**

----------------------------------------
Currently, the user needs to modify the changelog (or changelogs in case of multidistribution)  prior to make a release. If not, jenkins will complain at the end of the release process which is pretty annoying.

An automatic way of doing these changelog changes would be great.

**Comment by j-rivero** [comment]
duplicate of #246
