### ISSUE TITLE
Set bitbucket build status for default and release branch builds

### ISSUE THREAD

**Issue by osrf-migration** [ignition-tooling/release-tools#107]
**Original report ([archived issue](https://osrf-migration.github.io/ignition-tooling-gh-pages/#!/osrf/release-tools/issues/107)) by Steve Peters (Bitbucket: [Steven Peters](https://bitbucket.org/%7B2ccfed09-18b8-4921-8d58-15ef01092802%7D/)).**

----------------------------------------
We currently set the bitbucket build status for the `ci-pr_any` builds, but it would be nice to have it for the default and release branch builds, so we can browse recent jenkins builds from the commit view in bitbucket.

For example, `ign-math` has lots of build status because it has pipelines and appveyor testing enabled:

* https://bitbucket.org/ignitionrobotics/ign-math/commits/branch/ign-math3

but `ign-msgs` only has jenkins builds enabled:

* https://bitbucket.org/ignitionrobotics/ign-msgs/commits/branch/default

**Comment by j-rivero** [comment]
bitbucket is gone for us.
