### ISSUE TITLE
Missing dependencies for ignition_common-ci-pr_any-windows7-amd64

### ISSUE THREAD

**Issue by osrf-migration** [ignition-tooling/release-tools#108]
**Original report ([archived issue](https://osrf-migration.github.io/ignition-tooling-gh-pages/#!/osrf/release-tools/issues/108)) by Louise Poubel (Bitbucket: [chapulina](https://bitbucket.org/%7B5cfa2075-477b-4ded-bdb9-8d2479544ec4%7D/), GitHub: [chapulina](https://github.com/chapulina)).**

----------------------------------------
See this PR:

https://bitbucket.org/ignitionrobotics/ign-common/pull-requests/33/isolate-classes-which-are-failing-on-our/diff

**Comment by j-rivero** [comment]
fixed a while a go.
