### ISSUE TITLE
Separate packages.osrfoundation.org from build.osrfoundation.org

### ISSUE THREAD

**Issue by osrf-migration** [ignition-tooling/release-tools#114]
**Original report ([archived issue](https://osrf-migration.github.io/ignition-tooling-gh-pages/#!/osrf/release-tools/issues/114)) by Steve Peters (Bitbucket: [Steven Peters](https://bitbucket.org/%7B2ccfed09-18b8-4921-8d58-15ef01092802%7D/)).**

----------------------------------------
The jenkins master at build.osrfoundation.org is frequently going offline due to a lack of disk space. The bulk of the space is occupied by packages and files hosted at packages.osrfoundation.org.

Should we just separate these into two separate machines? It's really annoying for the buildfarm to keep going offline.

**Comment by j-rivero** [comment]
On production.
