### ISSUE TITLE
SDFORMAT_MAJOR_VERSION not set in gazebo multi-any jobs

### ISSUE THREAD

**Issue by osrf-migration** [ignition-tooling/release-tools#115]
**Original report ([archived issue](https://osrf-migration.github.io/ignition-tooling-gh-pages/#!/osrf/release-tools/issues/115)) by Steve Peters (Bitbucket: [Steven Peters](https://bitbucket.org/%7B2ccfed09-18b8-4921-8d58-15ef01092802%7D/)).**

----------------------------------------
The [gazebo-ci-pr_any+sdformat_any+ign_any-xenial-amd64-gpu-nvidia](https://build.osrfoundation.org/job/gazebo-ci-pr_any+sdformat_any+ign_any-xenial-amd64-gpu-nvidia/) job builds gazebo with sdformat and some ignition packages from source. @iche033 recently tried building a branch of `gazebo7` it with a custom branch of  `sdf4` and `ign-math2`, but it failed while trying to install dependencies.

* https://build.osrfoundation.org/job/gazebo-ci-pr_any+sdformat_any+ign_any-xenial-amd64-gpu-nvidia/5/

I believe it failed because the `SDFORMAT_MAJOR_VERSION` variable wasn't set when [boilerplate_prepare.sh is called in gazebo-base-default.bash](https://github.com/ignition-tooling/release-tools/blob/d7d042d9bf1c0fcd1780572f1d4cac9ed8f8e0ab/jenkins-scripts/docker/lib/gazebo-base-default.bash#L22), so it defaulted to major version 5. I made a test branch with a different default value for @iche033 to get his test running, but it would be nice if we could handle this better. Maybe we need an extra if block where we check if sdformat is being built and call an sdformat_version_hook if so.

**Comment by scpeters** [comment]
we aren't using these jobs anymore
