### ISSUE TITLE
Force docker cache invalidation

### ISSUE THREAD

**Issue by osrf-migration** [ignition-tooling/release-tools#121]
**Original report ([archived issue](https://osrf-migration.github.io/ignition-tooling-gh-pages/#!/osrf/release-tools/issues/121)) by Steve Peters (Bitbucket: [Steven Peters](https://bitbucket.org/%7B2ccfed09-18b8-4921-8d58-15ef01092802%7D/)).**

----------------------------------------
We made a new release of sdformat4 in order to access a new feature that hadn't been released yet in sdformat5. Due to a quirk of the debian metadata, the `libsdformat4-dev` installs the `sdformat-sdf` version 5.2 package, which didn't have that new feature. So I released `sdformat-sdf` version 5.3 with the feature, but the docker cache didn't notice the new package so the test continues to fail:

* https://build.osrfoundation.org/job/gazebo-ci-pr_any-xenial-amd64-gpu-nvidia/349/testReport/junit/(root)/PhysicsEngines_AttachLightTest/LinkLight_0/

I'm going to try a custom branch of release-tools to invalidate the cache.

**Comment by j-rivero** [comment]
There is a hidden variable called `INVALIDATE_DOCKER_CACHE`that can be injected as a quick workaround. Real problems with docker cache should be reported independently and solved.
