### ISSUE TITLE
Build flow plugin has security vulnerability and is deprecated

### ISSUE THREAD

**Issue by osrf-migration** [ignition-tooling/release-tools#124]
**Original report ([archived issue](https://osrf-migration.github.io/ignition-tooling-gh-pages/#!/osrf/release-tools/issues/124)) by Steve Peters (Bitbucket: [Steven Peters](https://bitbucket.org/%7B2ccfed09-18b8-4921-8d58-15ef01092802%7D/)).**

----------------------------------------
https://wiki.jenkins.io/display/JENKINS/Build+Flow+Plugin

Users are instructed to migrate to [pipeline plugin](https://wiki.jenkins-ci.org/display/JENKINS/Pipeline+Plugin).

@\_jrivero_ are we using the Build Flow Plugin?

**Comment by j-rivero** [comment]
uninstalled
