### ISSUE TITLE
[Build cop] Gazebo coverage configuration error

### ISSUE THREAD

**Issue by osrf-migration** [ignition-tooling/release-tools#125]
**Original report ([archived issue](https://osrf-migration.github.io/ignition-tooling-gh-pages/#!/osrf/release-tools/issues/125)) by Louise Poubel (Bitbucket: [chapulina](https://bitbucket.org/%7B5cfa2075-477b-4ded-bdb9-8d2479544ec4%7D/), GitHub: [chapulina](https://github.com/chapulina)).**

----------------------------------------
[This new job](https://build.osrfoundation.org/view/main/view/BuildCopFail/job/gazebo-ci-coverage-xenial-amd64-gpu-nvidia/1/console) failed at configure time:

~~~
cat: /var/lib/jenkins/bullseye-jenkins-license: No such file or directory
Build step 'Execute shell' marked build as failure
Recording test results
ERROR: Step ?Publish JUnit test result report? failed: No test report files were found. Configuration error?
Skipping publisher since build result is FAILURE
~~~

**Comment by j-rivero** [comment]
seems like an old problem with a machine provisioning. Should be fixed.
