### ISSUE TITLE
[Build cop] Gazebo 9 deb builder used to succeed, but is failing now

### ISSUE THREAD

**Issue by osrf-migration** [ignition-tooling/release-tools#126]
**Original report ([archived issue](https://osrf-migration.github.io/ignition-tooling-gh-pages/#!/osrf/release-tools/issues/126)) by Louise Poubel (Bitbucket: [chapulina](https://bitbucket.org/%7B5cfa2075-477b-4ded-bdb9-8d2479544ec4%7D/), GitHub: [chapulina](https://github.com/chapulina)).**

----------------------------------------
https://build.osrfoundation.org/view/main/view/BuildCopFail/job/gazebo9-debbuilder/246/console

**Comment by j-rivero** [comment]
fixed
