### ISSUE TITLE
Coverage build compilation fails

### ISSUE THREAD

**Issue by osrf-migration** [ignition-tooling/release-tools#129]
**Original report ([archived issue](https://osrf-migration.github.io/ignition-tooling-gh-pages/#!/osrf/release-tools/issues/129)) by Jose Luis Rivero (Bitbucket: [Jose Luis Rivero](https://bitbucket.org/%7Bd12309b2-f745-42ee-b119-aec4fcdf81fe%7D/)).**

----------------------------------------
I would say that it is a problem with our old version of bullseyes. Probably a good time to change the coverage system.

https://build.osrfoundation.org/job/gazebo-ci-coverage-xenial-amd64-gpu-nvidia/3/console

**Comment by j-rivero** [comment]
No coverage job in the buildfarm for gazebo anymore.
