### ISSUE TITLE
Compiler support for gazebo11

### ISSUE THREAD

**Issue by osrf-migration** [ignition-tooling/release-tools#137]
**Original report ([archived issue](https://osrf-migration.github.io/ignition-tooling-gh-pages/#!/osrf/release-tools/issues/137)) by Steve Peters (Bitbucket: [Steven Peters](https://bitbucket.org/%7B2ccfed09-18b8-4921-8d58-15ef01092802%7D/)).**

----------------------------------------
We are planning to use c++17 features in the experimental gazebo11 version, and this is pushing the limits of what is available. On bionic, gcc8 is ok, and Visual Studio 2017 (15.7) is ok, but the libc++ that ships with xcode9 on macOS high sierra doesn't have many c++17 features.

There is a [cryptic comment on stackoverflow](https://stackoverflow.com/a/50835358) claiming that xcode10 will contain the filesystem feature, so I installed the xcode 10 beta 2 on a test machine, but I didn't see any c++17 headers.

I'm currently testing a build of llvm from source (`brew install llvm --with-toolchain`), since c++17 support is present upstream. I'll see how difficult this is to support.

Related comment threads:

* https://bitbucket.org/osrf/sdformat/pull-requests/438/removal-of-boost/diff#comment-67720520
* https://bitbucket.org/ignitionrobotics/ign-transport/pull-requests/312/update-to-protobuf3-and-fix-compiler/diff#comment-67739406

**Comment by j-rivero** [comment]
solved a year ago.
