### ISSUE TITLE
Sanity checks for running release.py script

### ISSUE THREAD

**Issue by osrf-migration** [ignition-tooling/release-tools#14]
**Original report ([archived issue](https://osrf-migration.github.io/ignition-tooling-gh-pages/#!/osrf/release-tools/issues/14)) by Jose Luis Rivero (Bitbucket: [Jose Luis Rivero](https://bitbucket.org/%7Bd12309b2-f745-42ee-b119-aec4fcdf81fe%7D/)).**

----------------------------------------
When someone is using the release.py script to launch package buildings there is a good number of things which could drive the generation to fail. 

First brainstorm of checks I would consider useful:

1. Version provided is not exactly the same as one in top of changelogs of {sofware]-release repos.
1. Version already exists in the repository or source package exists in assets.
1. Package name do not correspond to the software being packaged.
1. Package alias do not correspond with proper {software}-release branch (prerelease o nightly).
1. Inconsistencies between software dependencies (control file) among branches: not the same dependencies in release, nightly and default.
1. Same version in dependencies (control file) for different distributions (i.e: boost for precise and quantal).

**Comment by j-rivero** [comment]
Done.
