### ISSUE TITLE
Store vcpkg dependencies (DEPEN_PKGS) in source repo instead of release-tools

### ISSUE THREAD

**Issue by osrf-migration** [ignition-tooling/release-tools#140]
**Original report ([archived issue](https://osrf-migration.github.io/ignition-tooling-gh-pages/#!/osrf/release-tools/issues/140)) by Steve Peters (Bitbucket: [Steven Peters](https://bitbucket.org/%7B2ccfed09-18b8-4921-8d58-15ef01092802%7D/)).**

----------------------------------------
For the windows jobs using colcon, we currently store the list of dependencies to install with vcpkg inside the release-tools build script for that package. I think that is brittle; it would be nicer to store it in a metadata file in the source repository.

https://github.com/ignition-tooling/release-tools/blob/b23b7b14ea0a050a6cd7f51e0a05784917a1c99d/jenkins-scripts/ign_gui-default-devel-windows-amd64.bat#L8

**Comment by j-rivero** [comment]
Approach has changed to use colcon + vcpkg dependencies
