### ISSUE TITLE
CI can't `hg pull` for pull requests from private forks

### ISSUE THREAD

**Issue by osrf-migration** [ignition-tooling/release-tools#145]
**Original report ([archived issue](https://osrf-migration.github.io/ignition-tooling-gh-pages/#!/osrf/release-tools/issues/145)) by Steve Peters (Bitbucket: [Steven Peters](https://bitbucket.org/%7B2ccfed09-18b8-4921-8d58-15ef01092802%7D/)).**

----------------------------------------
Here is an example of a pull request from a private fork to a public repo:

* https://bitbucket.org/osrf/subt/pull-requests/100/merge-private-into-public/diff

The jenkins build failed since it was unable to `hg pull` from the private repo:

* [![Build Status](https://build.osrfoundation.org/buildStatus/icon?job=subt-ci-pr_any-bionic-amd64&build=23)](https://build.osrfoundation.org/job/subt-ci-pr_any-bionic-amd64/23/) https://build.osrfoundation.org/job/subt-ci-pr_any-bionic-amd64/23/

One option would be to use the bitbucket API to get the diff proposed by the pull request and apply that to the target branch:

* https://api.bitbucket.org/2.0/repositories/osrf/subt/pullrequests/100/diff

For this specific pull request, I'm not worried about the CI, but I thought it would be good to be aware of this issue in case we get more pull requests from private forks.

**Comment by j-rivero** [comment]
private forks should be handled using the credentials plugin on Jenkins. Please open a new issue if we need it at some point.
