### ISSUE TITLE
Need to set USE_GCC8 variable in ignition-abichecker.bash

### ISSUE THREAD

**Issue by osrf-migration** [ignition-tooling/release-tools#152]
**Original report ([archived issue](https://osrf-migration.github.io/ignition-tooling-gh-pages/#!/osrf/release-tools/issues/152)) by Steve Peters (Bitbucket: [Steven Peters](https://bitbucket.org/%7B2ccfed09-18b8-4921-8d58-15ef01092802%7D/)).**

----------------------------------------
We are currently setting the `USE_GCC8` variable in the docker scripts for each ignition package:

* https://github.com/ignition-tooling/release-tools/blob/c67385d4136cf557d6700c386d18a20f3c15d0ea/jenkins-scripts/docker/ign_transport-compilation.bash#L33
* https://github.com/ignition-tooling/release-tools/blob/c67385d4136cf557d6700c386d18a20f3c15d0ea/jenkins-scripts/docker/ign_physics-compilation.bash#L21

This variable is never set in the [ignition-abichecker.bash](https://github.com/ignition-tooling/release-tools/blob/c67385d4136cf557d6700c386d18a20f3c15d0ea/jenkins-scripts/docker/ignition-abichecker.bash) script, though, so it is failing for various packages:

* [![Build Status](https://build.osrfoundation.org/buildStatus/icon?job=ignition_transport-abichecker-any_to_any-ubuntu_auto-amd64&build=11)](https://build.osrfoundation.org/job/ignition_transport-abichecker-any_to_any-ubuntu_auto-amd64/11/) https://build.osrfoundation.org/job/ignition_transport-abichecker-any_to_any-ubuntu_auto-amd64/11/
* [![Build Status](https://build.osrfoundation.org/buildStatus/icon?job=ignition_physics-abichecker-any_to_any-ubuntu_auto-amd64&build=33)](https://build.osrfoundation.org/job/ignition_physics-abichecker-any_to_any-ubuntu_auto-amd64/33/) https://build.osrfoundation.org/job/ignition_physics-abichecker-any_to_any-ubuntu_auto-amd64/33/

We could try looking in the pipeline script to see if it is installing gcc8?

cc @\_jrivero_

**Comment by j-rivero** [comment]
fixed
