### ISSUE TITLE
Consider "Execute concurrent builds if necessary" for ci-pr_any builds

### ISSUE THREAD

**Issue by osrf-migration** [ignition-tooling/release-tools#153]
**Original report ([archived issue](https://osrf-migration.github.io/ignition-tooling-gh-pages/#!/osrf/release-tools/issues/153)) by Steve Peters (Bitbucket: [Steven Peters](https://bitbucket.org/%7B2ccfed09-18b8-4921-8d58-15ef01092802%7D/)).**

----------------------------------------
I have noticed that the glados build machine will sometimes sit idle even when there is another ignition_gazebo-ci-pr_any-homebrew-amd64 job in the queue, if that same type of job is already running on sentinel. I think we would need to enable the "Execute concurrent builds if necessary" option to fix this.

cc @\_jrivero_

**Comment by j-rivero** [comment]
fixed https://github.com/ignition-tooling/release-tools/commit/712ec99776a1e125470f45b40c86239f2d8459ae
