### ISSUE TITLE
catkin tools is not python3 compatible

### ISSUE THREAD

**Issue by osrf-migration** [ignition-tooling/release-tools#157]
**Original report ([archived issue](https://osrf-migration.github.io/ignition-tooling-gh-pages/#!/osrf/release-tools/issues/157)) by Tully Foote (Bitbucket: [Tully Foote](https://bitbucket.org/%7B3d90dbd4-b845-466f-b5bd-068566f7ff50%7D/)).**

----------------------------------------
Digging into this followup [https://osrf-migration.github.io/ignition-tooling-gh-pages/#!/osrf/release-tools/pull-requests/948/use-python3-instead-of-python-except/diff#comment-138708097](https://osrf-migration.github.io/ignition-tooling-gh-pages/#!/osrf/release-tools/pull-requests/948/use-python3-instead-of-python-except/diff#comment-138708097) 

We have switched to use python3 by default. However python3-catkin-tools is uninstallable due to the unavailability of python3-trollius

The scripts support three build mechanisms. catkin\_make, catkin tools, and colcon. Because catkin tools can’t be run on our python3 platforms I’d suggest that we drop support for it and we can rely on either catkin\_make or colcon to provide coverage. 

And to that end I’d suggest that we use colcon as the default as it will be more forward looking for other integrations.

**Comment by j-rivero** [comment]
Merged and fixed.
