### ISSUE TITLE
Point get.gazebosim.org to github

### ISSUE THREAD

**Issue by scpeters** [ignition-tooling/release-tools#179]
Currently http://get.gazebosim.org redirects to https://bitbucket.org/osrf/release-tools/raw/default/one-line-installations/gazebo.sh

It should point to https://github.com/ignition-tooling/release-tools/raw/master/one-line-installations/gazebo.sh

**Comment by chapulina** [comment]
I fixed one of those here: https://bitbucket.org/osrf/gazebo_web_app/pull-requests/82/tutorials-and-models-from-github/diff#Lapp/controllers/home_controller.rbT249

**Comment by scpeters** [comment]
excellent; that should do it

we can close this once that is merged
