### ISSUE TITLE
Dependency on bitbucket-pipelines.yml should be removed

### ISSUE THREAD

**Issue by chapulina** [ignition-tooling/release-tools#203]
Several jobs rely on `bitbucket-pipelines.yml` to find out what Ubuntu distribution to use when running CI, for example:

https://github.com/ignition-tooling/release-tools/blob/8e8f5e4d2858de04643e666abd07772b156f98e6/jenkins-scripts/dsl/ignition.dsl#L241

Now that BitBucket is dead, we should get this information from somewhere else and remove those files from all projects.

**Comment by j-rivero** [comment]
as far as I can tell, it is used to sniff the testing platform defined there to be used in the CI jobs. If we remove this information we would need to retrieve the testing platform from elsewhere (github actions, define it in this repositorty?). This might be related to https://github.com/ignition-tooling/release-tools/issues/190
