### ISSUE TITLE
Console errors shouldn't be treated as errors

### ISSUE THREAD

**Issue by chapulina** [ignition-tooling/release-tools#205]
Some jobs, like the one below, display a list of "Identified problems" which includes output from `gzerr` / `ignerr`. But this kind of output shouldn't be treated as problems, because they are expected to show when testing failure conditions.

Having these listed on the CI output as problems is confusing, so we should remove them.

I'm not entirely sure where they're coming from though :thinking: :monocle_face: 

https://build.osrfoundation.org/job/ignition_gui-ci-pr_any-homebrew-amd64/420/

![iugnerr](https://user-images.githubusercontent.com/5751272/82379190-5a4b6700-99db-11ea-9eef-9b9456a057ec.png)

**Comment by scpeters** [comment]
I think it's from the following jenkins plugin:

* https://plugins.jenkins.io/build-failure-analyzer/

**Comment by j-rivero** [comment]
It is yes. I'm going to disable them in Jenkins configuration unless we find a better way of parsing that can not generate false positives.

**Comment by j-rivero** [comment]
removed.
