### ISSUE TITLE
Nightly builds are currently from blueprint; switch to citadel or dome?

### ISSUE THREAD

**Issue by scpeters** [ignition-tooling/release-tools#206]
Nightly builds are currently being run for blueprint packages; should we change this to citadel or dome to catch bugs in those packages?

https://github.com/ignition-tooling/release-tools/blob/master/jenkins-scripts/dsl/ignition_collection.dsl#L11-L26

**Comment by j-rivero** [comment]
fixed in #241 . The plan is to create nightlies at the beginning of development cycle to point always to the version to be released in the future.
