### ISSUE TITLE
Enable gazebo-simbody and gazebo-dart jobs

### ISSUE THREAD

**Issue by osrf-migration** [ignition-tooling/release-tools#21]
**Original report ([archived issue](https://osrf-migration.github.io/ignition-tooling-gh-pages/#!/osrf/release-tools/issues/21)) by Steve Peters (Bitbucket: [Steven Peters](https://bitbucket.org/%7B2ccfed09-18b8-4921-8d58-15ef01092802%7D/)).**

----------------------------------------
It would be helpful to know when upstream physics code causes gazebo physics test failures.

I can try this, but I want to make sure I don't fragment the repo. Should I use the minimize_workload branch or default?

**Comment by j-rivero** [comment]
Dart and Simbody packages are being installed in all our CI builds, I think that we don't need to do more related to this issue.
