### ISSUE TITLE
vrx, subt, and servicesim CI scripts still using bitbucket

### ISSUE THREAD

**Issue by scpeters** [ignition-tooling/release-tools#216]
* https://github.com/ignition-tooling/release-tools/blob/master/jenkins-scripts/dsl/vrx.dsl#L50-L77

* https://github.com/ignition-tooling/release-tools/blob/master/jenkins-scripts/dsl/subt.dsl#L92
* https://github.com/ignition-tooling/release-tools/blob/master/jenkins-scripts/dsl/subt.dsl#L127
* https://github.com/ignition-tooling/release-tools/blob/master/jenkins-scripts/dsl/subt.dsl#L169
* https://github.com/ignition-tooling/release-tools/blob/master/jenkins-scripts/dsl/subt.dsl#L203-L208

* https://github.com/ignition-tooling/release-tools/blob/master/jenkins-scripts/dsl/servicesim.dsl#L60-L77
* https://github.com/ignition-tooling/release-tools/blob/master/jenkins-scripts/dsl/servicesim.dsl#L114

**Comment by scpeters** [comment]
For reference, you can see how gazebo.dsl was updated to use GitHub in #176

**Comment by chapulina** [comment]
VRX and SubT were fixed in https://github.com/ignition-tooling/release-tools/pull/228.

I'd be ok not porting ServiceSim since we're no longer supporting it.
