### ISSUE TITLE
Add MSVC flags to windows compilations

### ISSUE THREAD

**Issue by osrf-migration** [ignition-tooling/release-tools#29]
**Original report ([archived issue](https://osrf-migration.github.io/ignition-tooling-gh-pages/#!/osrf/release-tools/issues/29)) by Jose Luis Rivero (Bitbucket: [Jose Luis Rivero](https://bitbucket.org/%7Bd12309b2-f745-42ee-b119-aec4fcdf81fe%7D/)).**

----------------------------------------
There are at least two levels to do add windows compilations flags:

* We can follow the current way of doing it for UNIX and add a CMAKE_CXX_FLAGS directive to our cmake files in the case of using MSVC.

* We can add the flags to our release-tools script, at the time of running cmake.

I would prefer the first option if we can not find a good reason to use the second one.

**Comment by j-rivero** [comment]
Flags are in use for MSVC
