### ISSUE TITLE
Dome support

### ISSUE THREAD

**Issue by j-rivero** [ignition-tooling/release-tools#297]
This ticket tracks Dome support for various platforms.

* See all supported platforms for Dome on [this page](https://ignitionrobotics.org/docs/dome).
* See the definition of Ignition's support categories on [this page](https://ignitionrobotics.org/docs/all/releases).

---

Operating System | Architecture | Packaging | CI | Functionality
---------------- | ------------ | --------- | -- | -------------
Ubuntu Bionic    | amd64        | ✅ Yes    | ✅ Yes, every pull request | ✅ All
.                | i386         | ✅ Yes    | No | ✅ All
.                | arm64        | ❓ Maybe  | No | Most low-level libraries known to work
.                | armhf        | ❓ Maybe  | No | Most low-level libraries known to work, DART physics engine not available
Ubuntu Focal     | amd64        | ✅ Yes    | ✅ Yes, every pull request | ✅ All
.                | arm64        | ❓ Maybe  | No | Most low-level libraries known to work
.                | armhf        | ❓ Maybe  | No | Most low-level libraries known to work, DART physics engine not available
Debian Buster    | amd64, i386, arm64, armhf | ❓ Maybe | No | Several libraries known to work
MacOS Catalina and BigSur | -   | ✅ Yes    | ✅ Yes, every pull request | Ignition only works in headless mode (GUI does not render; instead of using `ign gazebo fuel.sdf` command, use `ign gazebo -s fuel.sdf` to start the server only).
Windows 10       | .            | ❓ Maybe  | Some libraries tested on every pull request | Command line utilities are not supported. All packages up to but not including `ign-gazebo` are currently building. DART physics engine is not supported. Qt (GUI functionality) is not supported.

---

There are some problems affecting different platforms in Dome:

**Legend** :green_circle: in the repo :yellow_circle: waiting in the buildfarm :red_circle: requires action :black_circle: no release

 * **Ubuntu amd64 platforms:**
   * :green_circle: Focal/amd64
   * :green_circle: Bionic/amd64

 * **Ubuntu i386 platforms:**
   * :green_circle:  Bionic/i386:

* **Brew**
  * :green_circle: Bottles

 * **Ubuntu ARM platforms:**
   * :green_circle: Focal/arm64
   * :green_circle: Bionic/arm64

   * :black_circle: Focal/armhf:
     * Not supported (previous work: needs ign-gui4)

   * :black_circle: Bionic/armhf:
     * Not support (previous work: [missing dart packages from PPA are not in the repo](https://build.osrfoundation.org/job/ign-physics3-debbuilder/129/consoleFull#5247017446e2e1b04-6601-495c-8fb8-66d94e1f3e63))

 * **Debian i386 platforms:**
    * :black_circle: Not supported

 * **Debian amd64 platforms:**
   * :black_circle: Sid/*:
     * Not supported. Need to check conflicts with current libraries there
   * :red_circle: Buster/amd64:
      * [ ] Patching pending: needs code fixes in ign-transport9 to use the right zmq code, mostly port https://github.com/ignitionrobotics/ign-transport/pull/159 to work with Debian too (see also issue https://github.com/ignitionrobotics/ign-transport/issues/220).
        * debbuilder chain: [ign-transport9 ](https://build.osrfoundation.org/job/ign-transport9-debbuilder/148/consoleFull#-7817430426ea37b8d-a6d4-40ae-8431-d90c018842af)-> [ign-gui4](https://build.osrfoundation.org/view/All/job/ign-gui4-debbuilder/132/consoleFull#-6977271806e2e1b04-6601-495c-8fb8-66d94e1f3e63) -> [ign-gazebo4](https://build.osrfoundation.org/job/ign-gazebo4-debbuilder/135/consoleFull#18569794146e2e1b04-6601-495c-8fb8-66d94e1f3e63) 

 * **Debian ARM platforms:**
   * :yellow_circle: Buster/arm64
       * ign-math6 built. 

   * :red_circle:  Buster/armhf (raspbian)
       * [x] ign-plugin
         * [x] ogre-2.1
       * [ ] ign-rendering [![Build Status](https://build.osrfoundation.org/buildStatus/icon?job=ign-rendering3-debbuilder&build=50)](https://build.osrfoundation.org/job/ign-rendering3-debbuilder/50/) 
```
/usr/bin/ld: CMakeFiles/ignition-rendering3.dir/TransformController.cc.o:(.rodata+0x0): multiple definition of `typeinfo name for ignition::rendering::v3::Store<ignition::rendering::v3::Scene>'; CMakeFiles/ignition-rendering3.dir/OrbitViewController.cc.o:(.rodata+0x0): first defined here
/usr/bin/ld: CMakeFiles/ignition-rendering3.dir/TransformController.cc.o:(.data.rel.ro+0x0): multiple definition of `typeinfo for ignition::rendering::v3::Store<ignition::rendering::v3::Scene>'; CMakeFiles/ignition-rendering3.dir/OrbitViewController.cc.o:(.data.rel.ro+0x0): first defined here
```

**Comment by chapulina** [comment]
Why is `Buster/armhf` a candidate to exclusion? We already have some debs for it: 

![image](https://user-images.githubusercontent.com/5751272/95513142-af7a1c00-096e-11eb-8eef-47e0e1e7c91f.png)

**Comment by j-rivero** [comment]
> Why is `Buster/armhf` a candidate to exclusion? We already have some debs for it:

My impression is that the level of buster/armhf users does not worth the effort of the maintenance cost. Just an impression.

**Comment by chapulina** [comment]
> My impression is that the level of buster/armhf users does not worth the effort of the maintenance cost

Got it, I was mainly wondering if it was a technical reason. Agreed that we can leave it out for now.

**Comment by ruffsl** [comment]
Isn't the current version of raspbian based on buster?

* https://www.raspberrypi.org/blog/buster-the-new-version-of-raspbian/ 

Seems like that could shutout a lot of students using the default armhf image.

**Comment by j-rivero** [comment]
> Isn't the current version of raspbian based on buster?
> 
>     * https://www.raspberrypi.org/blog/buster-the-new-version-of-raspbian/
> 
> 
> Seems like that could shutout a lot of students using the default armhf image.

I think that there is a good reason to build them. Thanks Ruffin.

**Comment by j-rivero** [comment]
@chapulina my impression at this point would be to reduce the number of platforms supported to:
 * U, Focal (amd64, arm64)
 * U. Bionic (amd64, i386, arm64)
 * D. Buster (amd64, armhf)

Reasons are mainly maintenance costs (patches needed and releasing times for arm*) and no evidence of active use base for the rest of platforms at this moment.

**Comment by chapulina** [comment]
Ok, so you're suggesting we drop:

* U, Focal (armhf)
* U, Bionic (armhf)
* D, Buster (arm64. i386)

I think this is ok for now. If users come asking for other combinations we can look into it.

What do you think of updating the docs to include Buster once that's done?

https://ignitionrobotics.org/docs/dome/install

**Comment by scpeters** [comment]
I just saw a debbuild failure of ign-common3 on buster armhf:

* [![Build Status](https://build.osrfoundation.org/buildStatus/icon?job=ign-common3-debbuilder&build=975)](https://build.osrfoundation.org/job/ign-common3-debbuilder/975/) https://build.osrfoundation.org/job/ign-common3-debbuilder/975/

~~~
The following tests FAILED:
	  5 - UNIT_Console_TEST (Failed)
	  9 - UNIT_Filesystem_TEST (Failed)
	 66 - UNIT_ColladaLoader_TEST (Failed)
Errors while running CTest
~~~

maybe a filesystem or permissions problem?

**Comment by chapulina** [comment]
Closing this ticket as Dome is about to EOL (#600) and we've made the final releases. Here's the status of Linux releases at EOL:

![image](https://user-images.githubusercontent.com/5751272/147596480-ea049c0c-9d14-42db-992d-367f096ffc02.png)
