### ISSUE TITLE
Over-writing release hg tags

### ISSUE THREAD

**Issue by osrf-migration** [ignition-tooling/release-tools#30]
**Original report ([archived issue](https://osrf-migration.github.io/ignition-tooling-gh-pages/#!/osrf/release-tools/issues/30)) by Rich Mattes (Bitbucket: [richmattes](https://bitbucket.org/%7B1ef6f3dd-b8db-412b-94e9-e430e7aafd23%7D/)).**

----------------------------------------
I ran into a problem with while packaging sdformat 2.0.1 for Fedora, where the hg tag corresponsing to the 2.0.1 release seems to have moved.  I grabbed source corresponding to the sdformat2_2.0.1 tag at the end of August, with hg hash 7899c38774ac. Since then, it looks like the tag has moved a couple of times, and now points to d79259b which includes a fix to install the sdformat-version cmake file that was missing from the august tarball.

It's my understanding that the tag shifting was a bug with the release tools, and that they should be updated to not overwrite tags that already exist.

**Comment by j-rivero** [comment]
duplicate of #274
