### ISSUE TITLE
Migrate check_test.py to run on Windows

### ISSUE THREAD

**Issue by osrf-migration** [ignition-tooling/release-tools#31]
**Original report ([archived issue](https://osrf-migration.github.io/ignition-tooling-gh-pages/#!/osrf/release-tools/issues/31)) by Jose Luis Rivero (Bitbucket: [Jose Luis Rivero](https://bitbucket.org/%7Bd12309b2-f745-42ee-b119-aec4fcdf81fe%7D/)).**

----------------------------------------
It is currently using grep and xsltproc. We should find a way of running it on Windows, maybe trying to use python only code.

**Comment by scpeters** [comment]
there are versions of `check_test_ran.py` that now run on windows
