### ISSUE TITLE
Generate nightlies from main branches

### ISSUE THREAD

**Issue by chapulina** [ignition-tooling/release-tools#319]
During Dome's development cycle, we started generating nightly releases for all the versions included in Dome. That is handy for CI and to make sure everything is in place for when we start making pre-releases.

Pinning the nightlies to a collection may not be the best use for them though. For libraries that aren't bumping their version in a collection (for example, `ign-math` was using the the released version 6 for all collections from Blueprint to Dome), we can already easily make stable and pre-releases for them. On the other hand, the upcoming version `ign-math7`, has no binaries for it.

With that in mind, it would be convenient to always generate nightlies from `main` branches, regardless of what collection they're in.

Currently, all `main` branches are being bumped to `(N+1).0.0~pre` versions, and they all have homebrew formulas (https://github.com/osrf/homebrew-simulation/pull/1177) and [release repositories](https://github.com/ignition-release).

I believe the logic needs to be updated here:

https://github.com/ignition-tooling/release-tools/blob/372e0b99d5d71fba4cd2bc919db1c4f19db845e4/jenkins-scripts/dsl/ignition_collection.dsl#L506

**Comment by scpeters** [comment]
What are the main benefits of making nightly builds? I can think of some possibilities:

* people can install them to run the latest code (does anyone actually do this?)
* they are like CI for our debian metadata so we can identify problems before making a prerelease (I think this is useful)

In either case, I think they are most useful for development of the next ignition collection. For example, is there any utility in building nightlies of `ignition-cmake3` or `ignition-math7` if we aren't planning to use that any time soon?

**Comment by chapulina** [comment]
> people can install them to run the latest code (does anyone actually do this?)

I don't know, I personally don't.

> is there any utility in building nightlies of ignition-cmake3 or ignition-math7 if we aren't planning to use that any time soon?

I think that figuring out what "soon" is is the tough part to figure out. We may suddenly need to slip in a last-minute version bump into a collection and realize that none of the infrastructure is there. I think this is the worst time to start creating new homebrew formulas, release repositories and bumping version numbers. In the past we've been all over the place when bumping versions and I'd like the process to be as straight-forward as possible in the future.

On the other hand, what would be the advantage of having `ign-math6` nightlies now? We can easily make pre-releases any time of the day, not only at night :wink:
