### ISSUE TITLE
drogon marks free disk space as N/A when out of space and doesn't take it self offline automatically

### ISSUE THREAD

**Issue by scpeters** [ignition-tooling/release-tools#342]
Today, I saw a number of jobs fail on drogon, with the problem causing the failure identified as "No more disk space left in the Jenkins Node".

<img width="1058" alt="Screen Shot 2020-11-15 at 11 33 32 PM" src="https://user-images.githubusercontent.com/3650755/99231332-555a4b00-27a5-11eb-937c-1b8d953bfc6c.png">

* https://build.osrfoundation.org/computer/linux-aws_drogon.nv.xenial/
* https://build.osrfoundation.org/job/ignition_rendering2-install-pkg-bionic-amd64/503/

When I looked at the [list of nodes](https://build.osrfoundation.org/computer/), the "Free disk space" column says "N/A" for drogon.

<img width="1155" alt="Screen Shot 2020-11-15 at 11 33 19 PM" src="https://user-images.githubusercontent.com/3650755/99231196-204df880-27a5-11eb-9d27-27a8cce788fb.png">

I manually took the node offline, but I think it should be configured to take itself offline if its disk space gets too low?

**Comment by scpeters** [comment]
I just saw this happen again, with drogon reporting Free Disk Space as `N/A` when it appears to be out of disk space and failing a job but not marking itself offline

https://build.osrfoundation.org/job/ignition_gazebo-ci-pr_any-ubuntu_auto-amd64/4950/console

<img width="1147" alt="Screen Shot 2020-12-30 at 2 33 12 AM" src="https://user-images.githubusercontent.com/3650755/103346215-38719280-4a48-11eb-8ca1-e215a80d4c35.png">

**Comment by chapulina** [comment]
Not happening in a while
