### ISSUE TITLE
Migrate -doc jobs to a new s3 location?

### ISSUE THREAD

**Issue by osrf-migration** [ignition-tooling/release-tools#35]
**Original report ([archived issue](https://osrf-migration.github.io/ignition-tooling-gh-pages/#!/osrf/release-tools/issues/35)) by Jose Luis Rivero (Bitbucket: [Jose Luis Rivero](https://bitbucket.org/%7Bd12309b2-f745-42ee-b119-aec4fcdf81fe%7D/)).**

----------------------------------------
As a result of [pull request #53](https://osrf-migration.github.io/ignition-tooling-gh-pages/#!/osrf/release-tools/pull-requests/53), we probably need to migrate the -doc jobs (doxygen generated documentation) to a new place.

@nkoenig cpuld you confirm this and point to the new place if needed?

**Comment by j-rivero** [comment]
The generation of documentation is no longer in the buildfarm.
