### ISSUE TITLE
Generate optitrackBridge.exe automatically

### ISSUE THREAD

**Issue by osrf-migration** [ignition-tooling/release-tools#36]
**Original report ([archived issue](https://osrf-migration.github.io/ignition-tooling-gh-pages/#!/osrf/release-tools/issues/36)) by Carlos Agüero (Bitbucket: [caguero](https://bitbucket.org/%7Bda8a8e89-4bb0-421b-bd0e-dbbed3d4ed6a%7D/), GitHub: [caguero](https://github.com/caguero)).**

----------------------------------------
Instructions are [here](https://bitbucket.org/osrf/handsim/src/b641e22241cc78745b90049df3420a93d5f0aed5/windows/README.md?at=default)

Ideally, when the .exe is ready we should create a zip with [these libraries](https://www.dropbox.com/s/tkc25e1pzn4lm8f/bridgeLibs.zip?dl=0) inside.

**Comment by scpeters** [comment]
this project has been over for a while
