### ISSUE TITLE
Bump in Edifice: common4

### ISSUE THREAD

**Issue by chapulina** [ignition-tooling/release-tools#361]
Bump edifice to use `ign-common4` and `ign-fuel-tools6`.

The script in https://github.com/ignition-tooling/release-tools/pull/333 should be helpful.

https://github.com/ignition-tooling/release-tools/issues/331 may also be a helpful reference.

**Comment by scpeters** [comment]
for osrf/homebrew-simulation, I think we need an ignition-common4 formula first, and it would be easier if we combined all those pull requests that update dependencies into a single PR, since new bottles need to be built at the same time

**Comment by chapulina** [comment]
> we need an ignition-common4 formula first

Ahh it was there, I just forgot to open the PR: https://github.com/osrf/homebrew-simulation/pull/1308

>  it would be easier if we combined all those pull requests that update dependencies into a single PR

I originally kept them separate because I remember having trouble with a single PR. But if that's preferred I can combine them like I've been doing for `release-tools` and `gazebodistro`.

The tricky part is having all CI green before merging each source code PR, which requires nightlies for dependencies...

**Comment by scpeters** [comment]
> The tricky part is having all CI green before merging each source code PR, which requires nightlies for dependencies...

the alternative is to disable bottles by deleting the bottle block in affected formulae; then you can update formaule incrementally, but this has an effect of making our CI slow as well. we can also do a combination; disable bottles for edifice, launch, and gazebo, then update their dependencies all at once. it just depends on which package is the most problematic
