### ISSUE TITLE
Bump in Edifice: msgs7 and transport10

### ISSUE THREAD

**Issue by chapulina** [ignition-tooling/release-tools#362]
Bump edifice to use `ign-msgs7` and `ign-transport10`.

The script in https://github.com/ignition-tooling/release-tools/pull/333 should be helpful.

https://github.com/ignition-tooling/release-tools/issues/331 may also be a helpful reference.

**Comment by iche033** [comment]
just noticed that edifice uses `ignition-fuel_tools5` which pulls in `ignition-msgs6`.  We may need to consider also bumping edifice to use `ignition-fuel_tools6` and update its msgs dependency to 7

**Comment by chapulina** [comment]
All PRs needed to bump to `ign-msgs7`, and consequently `ign-transport10` and `ign-fuel-tools6`, are open and referenced above.

I opened them using the script from https://github.com/ignition-tooling/release-tools/pull/333 and some manual cleanup. The manual cleanup was needed mainly on the `homebrew-simulation` PRs.

Most of these PRs will need to be merged at the same time,  so we don't end up in a broken state.

**Comment by chapulina** [comment]
Order:

- [x] Merge docs
- [ ] Merge new homebrew formulae
- [ ] Merge dep bumps in homebrew, release-tools and gazebodistro
- [ ] Trigger new CI for `ign-transport` and `ign-fuel-tools`
- [ ] Merge `ign-transport` and `ign-fuel-tools` source code
- [ ] Trigger new CI for `ign-gui` and `ign-sensors`
- [ ] Merge `ign-gui` and `ign-sensors` source code
- [ ] Trigger new CI for `ign-gazebo` and `ign-launch`
- [ ] Merge `ign-gazebo` and `ign-launch` source code
- [ ] Merge `ign-edifice` source code
- [ ] Merge all `-release`
