### ISSUE TITLE
Make windows zip file during release process

### ISSUE THREAD

**Issue by osrf-migration** [ignition-tooling/release-tools#45]
**Original report ([archived issue](https://osrf-migration.github.io/ignition-tooling-gh-pages/#!/osrf/release-tools/issues/45)) by Steve Peters (Bitbucket: [Steven Peters](https://bitbucket.org/%7B2ccfed09-18b8-4921-8d58-15ef01092802%7D/)).**

----------------------------------------
The [sdformat build script uses an ign-math zip file](https://github.com/ignition-tooling/release-tools/blob/35743fcf69eb7cdff8dca07df7e24a517fdd1d8b/jenkins-scripts/lib/sdformat-base-windows.bat#L51), but we are currently generating this manually. We should automate this as part of the release process.

**Comment by j-rivero** [comment]
We don't really want to use zips as part of our releasing procedures.
