### ISSUE TITLE
ign-cmake requires component versions to match but debian metadata doesn't

### ISSUE THREAD

**Issue by scpeters** [ignition-tooling/release-tools#469]
I recently saw a user report about a configration error in `gazebo_ros` when trying to `find_package(Gazebo)` related to different installed versions of `libignition-common3*` packages. In this case, the `libignition-common3` and `libignition-common3-core-dev` have version 3.13.2, while all the other components have version 3.13.0. This leads to a cmake error due to a requirement in ign-cmake that [all components have the same exact version as the core library](https://github.com/ignitionrobotics/ign-cmake/blob/ignition-cmake2_2.8.0/cmake/ignition-config.cmake.in#L168). This becomes a problem because there is not such constraint expressed in the [debian metadata for ign-common3](https://github.com/ignition-release/ign-common3-release/blob/21ec15caba2e54f9fa4b4659e73783ede42c0d35/ubuntu/debian/control) (it does constrain the `-dev` packages to [match their corresponding `lib` package](https://github.com/ignition-release/ign-common3-release/blob/21ec15caba2e54f9fa4b4659e73783ede42c0d35/ubuntu/debian/control#L157), but there aren't constraints between component libraries).

~~~
--- stderr: gazebo_ros                                                                                                                                   
CMake Error at /usr/share/cmake-3.16/Modules/CMakeFindDependencyMacro.cmake:47 (find_package):
  Could not find a configuration file for package "ignition-common3-graphics"
  that exactly matches requested version "3.13.2".
  The following configuration files were considered but not accepted:
    /usr/lib/x86_64-linux-gnu/cmake/ignition-common3-graphics/ignition-common3-graphics-config.cmake, version: 3.13.0
Call Stack (most recent call first):
  /usr/lib/x86_64-linux-gnu/cmake/ignition-common3/ignition-common3-config.cmake:203 (find_dependency)
  /usr/lib/x86_64-linux-gnu/cmake/gazebo/gazebo-config.cmake:250 (find_package)
  ws/install/gazebo_dev/share/gazebo_dev/cmake/gazebo_dev-extras.cmake:2 (find_package)
  ws/install/gazebo_dev/share/gazebo_dev/cmake/gazebo_devConfig.cmake:41 (include)
  CMakeLists.txt:26 (find_package)
---
Failed   <<< gazebo_ros [6.49s, exited with code 1]
~~~

~~~
$ dpkg-query --list | grep libignition-common3 
ii  libignition-common3:amd64                     3.13.2-1~focal                                      amd64        Ignition Common classes and functions for robot apps - Shared library 
ii  libignition-common3-av:amd64                  3.13.0-1~focal                                      amd64        Ignition Common classes and functions (AV) - Shared library 
ii  libignition-common3-av-dev:amd64              3.13.0-1~focal                                      amd64        Ignition Common classes and functions (AV) - Development files 
ii  libignition-common3-core-dev:amd64            3.13.2-1~focal                                      amd64        Ignition Common classes and functions (core) - Development files 
ii  libignition-common3-dev:amd64                 3.13.0-1~focal                                      amd64        Ignition Common classes and functions for robot apps - Metapackage 
ii  libignition-common3-events:amd64              3.13.0-1~focal                                      amd64        Ignition Common classes and functions (Events) - Shared library 
ii  libignition-common3-events-dev:amd64          3.13.0-1~focal                                      amd64        Ignition Common classes and functions (Events) - Development files 
ii  libignition-common3-graphics:amd64            3.13.0-1~focal                                      amd64        Ignition Common classes and functions (Graphics) - Shared library 
ii  libignition-common3-graphics-dev:amd64        3.13.0-1~focal                                      amd64        Ignition Common classes and functions (Graphics) - Development files 
ii  libignition-common3-profiler:amd64            3.13.0-1~focal                                      amd64        Ignition Common classes and functions (Profiler) - Shared library 
ii  libignition-common3-profiler-dev:amd64        3.13.0-1~focal                                      amd64        Ignition Common classes and functions (profiler) - Development files
~~~

**Comment by j-rivero** [comment]
With current setup, dependency chain is more flexible but I think that we can not assure that a particular version of the library X.Y.Z is going to make API fully compatible with X.W.V (adding new features that don't break current API could require to have all the components in the same version to make them work properly). Following semantic versioning, we could probably relax the restriction on ign-cmake to match MAJOR.MINOR and leave PATCH out of the check, I don't think that we can relax it to go without only MAJOR.

Quickest solution by now is to make components to depend on the binary versions, [opencv is doing the same for official Debian packages](https://salsa.debian.org/science-team/opencv/-/blob/master/debian/control#L81-102). 

Code changes are trivial https://github.com/ignition-release/ign-common3-release/pull/1 , we will need to run a new release bumping just the release number or wait until the next release.

**Comment by scpeters** [comment]
> Code changes are trivial [ignition-release/ign-common3-release#1](https://github.com/ignition-release/ign-common3-release/pull/1) , we will need to run a new release bumping just the release number or wait until the next release.

thanks! I just tested that branch with ign-common3 3.13.2-2 and it looks good, so I approved and merged the PR. I'll work on forward-porting the changes to ignition-common4 and then assess which other packages should be updated

**Comment by scpeters** [comment]
> I'll work on forward-porting the changes to ignition-common4 and then assess which other packages should be updated

https://github.com/ignition-release/ign-common4-release/pull/5

**Comment by scpeters** [comment]
it looks like the metadata is already in place for the eigen component of math6:

* https://github.com/ignition-release/ign-math6-release/blob/main/ubuntu/debian/control#L38

**Comment by scpeters** [comment]
> it looks like the metadata is already in place for the eigen component of math6:
> 
> * https://github.com/ignition-release/ign-math6-release/blob/main/ubuntu/debian/control#L38

and math7 as well:

* https://github.com/ignition-release/ign-math7-release/blob/main/ubuntu/debian/control#L38

**Comment by scpeters** [comment]
release-repos to update (only those with ign-cmake components):

* [X] ign-cmake: only a single debian package `libignition-cmake2-dev` for all components
* [ ] ign-common
* [ ] ign-gazebo
* [ ] ign-math
* [ ] ign-msgs
* [ ] ign-physics
* [X] ign-plugin: only a single debian package `libignition-plugin-dev` for all components
* [ ] ign-rendering
* [ ] ign-sensors
* [ ] ign-transport
* [ ] ign-utils

**Comment by scpeters** [comment]
I think each version of ignition-transport will need the fix:

* https://github.com/ignition-release/ign-transport10-release/blob/fb1f1ca97b7dab9db5a97da8e3e0ad8d854be051/ubuntu/debian/control#L55

**Comment by scpeters** [comment]
ign-physics versions will need the fix:

* https://github.com/ignition-release/ign-physics4-release/blob/b37a33762d1bb53c5009ae232d2c8ae09d440d95/ubuntu/debian/control#L49

**Comment by scpeters** [comment]
rendering and sensors need the fix too

* rendering: https://github.com/ignition-release/ign-rendering5-release/blob/75a7f31ea39061a3518e2be7b10d8cde9d456f01/ubuntu/debian/control#L66
* sensors: https://github.com/ignition-release/ign-sensors5-release/blob/main/ubuntu/debian/control#L60

**Comment by scpeters** [comment]
rebuilding ign-transport8 on focal:

* [![Build Status](https://build.osrfoundation.org/buildStatus/icon?job=ign-transport8-debbuilder&build=57)](https://build.osrfoundation.org/job/ign-transport8-debbuilder/57/) https://build.osrfoundation.org/job/ign-transport8-debbuilder/57/

**Comment by chapulina** [comment]
@scpeters , are you planning to address the 3 remaining libraries?

**Comment by scpeters** [comment]
> @scpeters , are you planning to address the 3 remaining libraries?

yes, I will start working on this

**Comment by scpeters** [comment]
fixes are now merged or in pull requests for all affected packages
