### ISSUE TITLE
New collection: Garden 🌱

### ISSUE THREAD

**Issue by chapulina** [ignition-tooling/release-tools#527]
- [x] Create `gazebodistro` file for new collection ([example](https://github.com/ignition-tooling/gazebodistro/pull/11))
- [x] Create `ign-<collection>` and `ign-<collection>-release` repositories ([example source](https://github.com/ignitionrobotics/ign-edifice), [example release](https://github.com/ignition-release/ign-edifice-release))
- [x] Create homebrew-simulation formula for new collection ([example](https://github.com/osrf/homebrew-simulation/pull/1173))
- [x] Create collection view on release-tools and build nightlies https://github.com/ignition-tooling/release-tools/pull/546
- [x] Add collection to buildfarmer dashboard ([example](https://github.com/osrf/buildfarmer/pull/183)) / scripts ([example](https://github.com/osrf/buildfarmer/pull/184))
- [x] Add docs for new collection ([example](https://github.com/ignitionrobotics/docs/pull/95))
- [x] Add new collection label:
    - [x] Add to pr-collection-labeler ([example](https://github.com/ignition-tooling/pr-collection-labeler/pull/11))
    - [x] Add to all libraries ([handy script](https://github.com/chapulina/github-label-maker/tree/chapulina/ign#ignition))
- [x] Add new collection tag to Gazebo Answers [here](https://answers.gazebosim.org/settings/FORUM_DATA_RULES/)

**Comment by scpeters** [comment]
creating Garden collection in https://github.com/ignition-tooling/release-tools/pull/546, but not yet building nightlies

**Comment by scpeters** [comment]
> creating Garden collection in #546, but not yet building nightlies

actually started building nightlies in that PR too

**Comment by chapulina** [comment]
Thanks, @scpeters , that checks the last box :heavy_check_mark:
