### ISSUE TITLE
Bump in Garden: ign-rendering and dependents

### ISSUE THREAD

**Issue by scpeters** [ignition-tooling/release-tools#545]
This is similar to https://github.com/ignition-tooling/release-tools/issues/331

Libraries being bumped:

* ignition-rendering7: needed to support wide-angle cameras, which require new virtual functions in Scene.hh
  * Dependents:
    * ignition-gui7
    * ignition-sensors7
    * ignition-gazebo7
    * ignition-launch6

* ign-rendering7: needed to support wide-angle cameras, which require new virtual functions in Scene.hh
    - [x] Source code of all downstream libraries ([example](https://github.com/ignitionrobotics/ign-transport/pull/149))
    - [x] Release repositories of all downstream libraries ([example](https://github.com/ignition-release/ign-fuel-tools7-release/pull/1))
    - [x] Use `main` branch on `gazebodistro` ([example](https://github.com/ignition-tooling/gazebodistro/pull/42))
    - [x] Build nightlies from the `main` branch ([example](https://github.com/ignition-tooling/release-tools/pull/437)) https://github.com/ignition-tooling/release-tools/pull/558
    - [ ] I think this is not needed for ign-rendering, but only for its dependents ~~Update gzdev to use nightlies on CI ([example](https://github.com/ignition-tooling/gzdev/pull/31))~~
    - [x] homebrew-simulation: create formula and update dependencies ([example](https://github.com/osrf/homebrew-simulation/pull/14230)) https://github.com/osrf/homebrew-simulation/pull/1685
    - [x] docs (the collection’s page) ([example](https://github.com/ignitionrobotics/docs/pull/175)) https://github.com/ignitionrobotics/docs/pull/216

* ign-gui7
    - [x] Source code of all downstream libraries ([example](https://github.com/ignitionrobotics/ign-transport/pull/149))
    - [x] Release repositories of all downstream libraries ([example](https://github.com/ignition-release/ign-fuel-tools7-release/pull/1))
    - [x] Use `main` branch on `gazebodistro` ([example](https://github.com/ignition-tooling/gazebodistro/pull/42))
    - [x] Build nightlies from the `main` branch ([example](https://github.com/ignition-tooling/release-tools/pull/437))
    - [x] Update gzdev to use nightlies on CI ([example](https://github.com/ignition-tooling/gzdev/pull/31)) https://github.com/ignition-tooling/gzdev/pull/40
    - [x] homebrew-simulation: create formula and update dependencies ([example](https://github.com/osrf/homebrew-simulation/pull/14230))
    - [x] docs (the collection’s page) ([example](https://github.com/ignitionrobotics/docs/pull/175)) https://github.com/ignitionrobotics/docs/pull/216

* ign-sensors7
    - [x] Source code of all downstream libraries ([example](https://github.com/ignitionrobotics/ign-transport/pull/149))
    - [x] Release repositories of all downstream libraries ([example](https://github.com/ignition-release/ign-fuel-tools7-release/pull/1))
    - [x] Use `main` branch on `gazebodistro` ([example](https://github.com/ignition-tooling/gazebodistro/pull/42))
    - [x] Build nightlies from the `main` branch ([example](https://github.com/ignition-tooling/release-tools/pull/437))
    - [x] Update gzdev to use nightlies on CI ([example](https://github.com/ignition-tooling/gzdev/pull/31)) https://github.com/ignition-tooling/gzdev/pull/40
    - [x] homebrew-simulation: create formula and update dependencies ([example](https://github.com/osrf/homebrew-simulation/pull/14230))
    - [x] docs (the collection’s page) ([example](https://github.com/ignitionrobotics/docs/pull/175)) https://github.com/ignitionrobotics/docs/pull/216

* ign-gazebo7
    - [x] Source code of all downstream libraries ([example](https://github.com/ignitionrobotics/ign-transport/pull/149))
    - [x] Release repositories of all downstream libraries ([example](https://github.com/ignition-release/ign-fuel-tools7-release/pull/1))
    - [x] Use `main` branch on `gazebodistro` ([example](https://github.com/ignition-tooling/gazebodistro/pull/42))
    - [x] Build nightlies from the `main` branch ([example](https://github.com/ignition-tooling/release-tools/pull/437))
    - [x] Update gzdev to use nightlies on CI ([example](https://github.com/ignition-tooling/gzdev/pull/31)) https://github.com/ignition-tooling/gzdev/pull/40
    - [x] homebrew-simulation: create formula and update dependencies ([example](https://github.com/osrf/homebrew-simulation/pull/14230)) https://github.com/osrf/homebrew-simulation/pull/1684
    - [x] docs (the collection’s page) ([example](https://github.com/ignitionrobotics/docs/pull/175)) https://github.com/ignitionrobotics/docs/pull/216

* ign-launch6
    - [x] Source code of all downstream libraries ([example](https://github.com/ignitionrobotics/ign-transport/pull/149))
    - [x] Release repositories of all downstream libraries ([example](https://github.com/ignition-release/ign-fuel-tools7-release/pull/1))
    - [x] Use `main` branch on `gazebodistro` ([example](https://github.com/ignition-tooling/gazebodistro/pull/42))
    - [x] Build nightlies from the `main` branch ([example](https://github.com/ignition-tooling/release-tools/pull/437))
    - [x] Update gzdev to use nightlies on CI ([example](https://github.com/ignition-tooling/gzdev/pull/31)) https://github.com/ignition-tooling/gzdev/pull/40
    - [x] homebrew-simulation: create formula and update dependencies ([example](https://github.com/osrf/homebrew-simulation/pull/14230))
    - [x] docs (the collection’s page) ([example](https://github.com/ignitionrobotics/docs/pull/175)) https://github.com/ignitionrobotics/docs/pull/216

**Comment by scpeters** [comment]
I just ran the `bump_dependency.bash` script, and I think there's room for improvement. I'll make some suggestions as I look over the process

**Comment by j-rivero** [comment]
>     * ignition-rendering7: needed to support wide-angle cameras, which require new virtual functions in Scene.hh

I really like this descriptions on why we need to bump majors. It could help a lot for many different things in the future. Would be great if we add them to every library bump.

**Comment by chapulina** [comment]
> I just ran the bump_dependency.bash script

Ouch, so the rest of the PRs weren't open? :cry:

**Comment by scpeters** [comment]
> > I just ran the bump_dependency.bash script
> 
> Ouch, so the rest of the PRs weren't open? 😢

I didn't open the homebrew pull requests because they were modifying the fortress formula instead of creating a new one

**Comment by chapulina** [comment]
> they were modifying the fortress formula instead of creating a new one for garden

ouch, I see :confused: Let me know if you need help navigating the messy script. For Fortress the script correctly created all these new formulae:

**Comment by scpeters** [comment]
@adlarkin I believe https://github.com/osrf/homebrew-simulation/pull/1685 is the first homebrew formula that we should merge

**Comment by scpeters** [comment]
> @adlarkin I believe [osrf/homebrew-simulation#1685](https://github.com/osrf/homebrew-simulation/pull/1685) is the first homebrew formula that we should merge

also https://github.com/ignition-tooling/release-tools/pull/558 will be needed so we can start building nightlies of ign-rendering7

**Comment by scpeters** [comment]
@adlarkin could you update `gzdev` to use nightlies following the pattern of https://github.com/ignition-tooling/gzdev/pull/31 ?

**Comment by scpeters** [comment]
> > they were modifying the fortress formula instead of creating a new one for garden
> 
> ouch, I see confused Let me know if you need help navigating the messy script. For Fortress the script correctly created all these new formulae:
> 
> https://github.com/osrf/homebrew-simulation/pulls?q=is%3Apr+bumps+in+fortress+is%3Aclosed+author%3Achapulina+

I've suggested some improvements to the `bump_dependency.bash` script for the homebrew formula generation in https://github.com/ignition-tooling/release-tools/pull/557

**Comment by scpeters** [comment]
> @adlarkin could you update `gzdev` to use nightlies following the pattern of [ignition-tooling/gzdev#31](https://github.com/ignition-tooling/gzdev/pull/31) ?

https://github.com/ignition-tooling/gzdev/pull/40

**Comment by scpeters** [comment]
started nightly builds for ign-gui7 and ign-sensors7 to we can move forward with ign-gazebo7

* [![Build Status](https://build.osrfoundation.org/buildStatus/icon?job=ign-gui7-debbuilder&build=15)](https://build.osrfoundation.org/view/ign-garden/job/ign-gui7-debbuilder/15/) https://build.osrfoundation.org/view/ign-garden/job/ign-gui7-debbuilder/15/
* [![Build Status](https://build.osrfoundation.org/buildStatus/icon?job=ign-gui7-debbuilder&build=16)](https://build.osrfoundation.org/view/ign-garden/job/ign-gui7-debbuilder/16) https://build.osrfoundation.org/view/ign-garden/job/ign-gui7-debbuilder/16
* [![Build Status](https://build.osrfoundation.org/buildStatus/icon?job=ign-sensors7-debbuilder&build=15)](https://build.osrfoundation.org/view/ign-garden/job/ign-sensors7-debbuilder/15/) https://build.osrfoundation.org/view/ign-garden/job/ign-sensors7-debbuilder/15/
* [![Build Status](https://build.osrfoundation.org/buildStatus/icon?job=ign-sensors7-debbuilder&build=16)](https://build.osrfoundation.org/view/ign-garden/job/ign-sensors7-debbuilder/16) https://build.osrfoundation.org/view/ign-garden/job/ign-sensors7-debbuilder/16

**Comment by scpeters** [comment]
started nightly builds for ign-gazebo7 after merging 

* [![Build Status](https://build.osrfoundation.org/buildStatus/icon?job=ign-gazebo7-debbuilder&build=17)](https://build.osrfoundation.org/view/ign-garden/job/ign-gazebo7-debbuilder/17/) https://build.osrfoundation.org/view/ign-garden/job/ign-gazebo7-debbuilder/17/
* [![Build Status](https://build.osrfoundation.org/buildStatus/icon?job=ign-gazebo7-debbuilder&build=18)](https://build.osrfoundation.org/view/ign-garden/job/ign-gazebo7-debbuilder/18) https://build.osrfoundation.org/view/ign-garden/job/ign-gazebo7-debbuilder/18

**Comment by chapulina** [comment]
> I think this is not needed for ign-rendering, but only for its dependents

It wasn't immediately necessary for this bump, but it was necessary for subsequent bumps in https://github.com/ignition-tooling/release-tools/issues/574. I think it's easier to maintain `gzdev` if we just enable nightlies for all `main` branches, or at least all the ones we're bumping, instead of analyzing case-by-case and having to revisit it for every bump.

Doing it in https://github.com/ignition-tooling/gzdev/pull/49

**Comment by scpeters** [comment]
> > I think this is not needed for ign-rendering, but only for its dependents
> 
> It wasn't immediately necessary for this bump, but it was necessary for subsequent bumps in #574. I think it's easier to maintain `gzdev` if we just enable nightlies for all `main` branches, or at least all the ones we're bumping, instead of analyzing case-by-case and having to revisit it for every bump.
> 
> Doing it in [ignition-tooling/gzdev#49](https://github.com/ignition-tooling/gzdev/pull/49)

sounds reasonable

**Comment by chapulina** [comment]
> sounds reasonable

Great! See

* https://github.com/ignition-tooling/gzdev/pull/50
* https://github.com/ignition-tooling/release-tools/pull/615
