### ISSUE TITLE
Bump in Garden: ign-msgs and dependents

### ISSUE THREAD

**Issue by chapulina** [ignition-tooling/release-tools#554]
To avoid conflicts, this ticket should be worked on after #545 is closed.

Libraries being bumped:

* `ign-msgs 9`: Various messages will be updated, for example https://github.com/ignitionrobotics/ign-msgs/pull/199, https://github.com/ignitionrobotics/ign-gazebo/issues/1156
    - [x] Source code of all downstream libraries ([example](https://github.com/ignitionrobotics/ign-transport/pull/149))
    - [x] Release repositories of all downstream libraries ([example](https://github.com/ignition-release/ign-fuel-tools7-release/pull/1))
    - [x] Use `main` branch on `gazebodistro` ([example](https://github.com/ignition-tooling/gazebodistro/pull/42))
    - [x] Build nightlies from the `main` branch ([example](https://github.com/ignition-tooling/release-tools/pull/437))
    - [x] Update gzdev to use nightlies on CI ([example](https://github.com/ignition-tooling/gzdev/pull/31))
    - [x] homebrew-simulation: create formula and update dependencies ([example](https://github.com/osrf/homebrew-simulation/pull/14230))
    - [x] docs (the collection’s page) ([example](https://github.com/ignitionrobotics/docs/pull/175))

* `ign-fuel-tools 8`: Depends on `ign-msgs`
    - [x] Source code of all downstream libraries ([example](https://github.com/ignitionrobotics/ign-transport/pull/149))
    - [x] Release repositories of all downstream libraries ([example](https://github.com/ignition-release/ign-fuel-tools7-release/pull/1))
    - [x] Use `main` branch on `gazebodistro` ([example](https://github.com/ignition-tooling/gazebodistro/pull/42))
    - [x] Build nightlies from the `main` branch ([example](https://github.com/ignition-tooling/release-tools/pull/437))
    - [x] Update gzdev to use nightlies on CI ([example](https://github.com/ignition-tooling/gzdev/pull/31))
    - [x] homebrew-simulation: create formula and update dependencies ([example](https://github.com/osrf/homebrew-simulation/pull/14230))
    - [x] docs (the collection’s page) ([example](https://github.com/ignitionrobotics/docs/pull/175))

* `ign-transport 12`: Depends on `ign-msgs`
    - [x] Source code of all downstream libraries ([example](https://github.com/ignitionrobotics/ign-transport/pull/149))
    - [x] Release repositories of all downstream libraries ([example](https://github.com/ignition-release/ign-fuel-tools7-release/pull/1))
    - [x] Use `main` branch on `gazebodistro` ([example](https://github.com/ignition-tooling/gazebodistro/pull/42))
    - [x] Build nightlies from the `main` branch ([example](https://github.com/ignition-tooling/release-tools/pull/437))
    - [x] Update gzdev to use nightlies on CI ([example](https://github.com/ignition-tooling/gzdev/pull/31))
    - [x] homebrew-simulation: create formula and update dependencies ([example](https://github.com/osrf/homebrew-simulation/pull/14230))
    - [x] docs (the collection’s page) ([example](https://github.com/ignitionrobotics/docs/pull/175))

Downstream affected libraries:

* `ign-gazebo 7`
* `ign-gui 7`
* `ign-launch 6`
* `ign-sensors 6`

**Comment by chapulina** [comment]
It may be possible to keep SDF at 12 even with `ign-cmake` and USD

**Comment by scpeters** [comment]
If it's not urgent, I can take a shot at https://github.com/ignition-tooling/release-tools/issues/564 before this to try to simplify our bumping process

**Comment by chapulina** [comment]
> If it's not urgent

It's becoming more pressing for some projects, but I'd say we can wait a week or so, is that enough?

**Comment by scpeters** [comment]
> > If it's not urgent
> 
> It's becoming more pressing for some projects, but I'd say we can wait a week or so, is that enough?

sure, I'll try next week and if I don't make progress we can continue the normal way

**Comment by adlarkin** [comment]
I'm not sure who's going to work on the bumps mentioned here, but to the person who does, it would be worth using the script modifications proposed in #557. I tested it for this issue (I didn't make any commits/PRs), and the results seemed okay - see https://github.com/ignition-tooling/release-tools/pull/557#issuecomment-976013874 for the command I ran that would create the PRs related to this issue.

**Comment by scpeters** [comment]
it's done!

**Comment by chapulina** [comment]
Thanks, @scpeters !

**Comment by scpeters** [comment]
I opened https://github.com/ignition-release/ign-garden-release/pull/3 to use symlinks in ign-garden-release as a follow-up https://github.com/ignition-release/ign-garden-release/pull/2 after noticing changes in multiple control files.

**Comment by chapulina** [comment]
> ign-msgs9 ... Update gzdev to use nightlies on CI 

This box was checked but it hadn't been done. Noticed while working on #574. Here's the PR:

* https://github.com/ignition-tooling/gzdev/pull/48
