### ISSUE TITLE
Bump in Garden: ign-math7 and dependents

### ISSUE THREAD

**Issue by chapulina** [ignition-tooling/release-tools#574]
Libraries being bumped:

`ign-math7`: The main motivation for a bump are are various static initialization issues being fixed on `ign-math7` that can't be backported to `ign-math6`.

Ignition Math is low-level enough that we shouldn't do this bump lightly. One thing to keep in mind is that a lot of APIs have been updated from v6 to v7 (see https://github.com/ignitionrobotics/ign-math/issues/301), so the bump will come with lots of deprecation warnings for all downstream libraries, plugins, etc.  If we'll go through the pain of handling all these deprecation warnings, I think we should consider completing the API updates for v7, so we deal with them all at once, and don't have another round of pain when v8 comes along. Having all the API consistent helps handling the deprecations more easily.

* `ign-math7`
    - [x] Source code of all downstream libraries ([example](https://github.com/ignitionrobotics/ign-transport/pull/149))
    - [x] Release repositories of all downstream libraries ([example](https://github.com/ignition-release/ign-fuel-tools7-release/pull/1))
    - [x] Use `main` branch on `gazebodistro` ([example](https://github.com/ignition-tooling/gazebodistro/pull/42))
    - [x] Build nightlies from the `main` branch ([example](https://github.com/ignition-tooling/release-tools/pull/437))
    - [x] Update gzdev to use nightlies on CI ([example](https://github.com/ignition-tooling/gzdev/pull/31))
    - [x] homebrew-simulation: create formula and update dependencies ([example](https://github.com/osrf/homebrew-simulation/pull/14230))
    - [x] docs (the collection’s page) ([example](https://github.com/ignitionrobotics/docs/pull/175))

* `ign-common5`: DEM support (https://github.com/ignitionrobotics/ign-common/pull/267)
    - [x] Source code of all downstream libraries ([example](https://github.com/ignitionrobotics/ign-transport/pull/149))
    - [x] Release repositories of all downstream libraries ([example](https://github.com/ignition-release/ign-fuel-tools7-release/pull/1))
    - [x] Use `main` branch on `gazebodistro` ([example](https://github.com/ignition-tooling/gazebodistro/pull/42))
    - [x] Build nightlies from the `main` branch ([example](https://github.com/ignition-tooling/release-tools/pull/437))
    - [x] Update gzdev to use nightlies on CI ([example](https://github.com/ignition-tooling/gzdev/pull/31))
    - [x] homebrew-simulation: create formula and update dependencies ([example](https://github.com/osrf/homebrew-simulation/pull/14230))
    - [x] docs (the collection’s page) ([example](https://github.com/ignitionrobotics/docs/pull/175))

* `sdformat13`: Depends on `ign-math`
    - [x] Source code of all downstream libraries ([example](https://github.com/ignitionrobotics/ign-transport/pull/149))
    - [x] Release repositories of all downstream libraries ([example](https://github.com/ignition-release/ign-fuel-tools7-release/pull/1))
    - [x] Use `main` branch on `gazebodistro` ([example](https://github.com/ignition-tooling/gazebodistro/pull/42))
    - [x] Build nightlies from the `main` branch ([example](https://github.com/ignition-tooling/release-tools/pull/437))
    - [x] Update gzdev to use nightlies on CI ([example](https://github.com/ignition-tooling/gzdev/pull/31))
    - [x] homebrew-simulation: create formula and update dependencies ([example](https://github.com/osrf/homebrew-simulation/pull/14230))
    - [x] docs (the collection’s page) ([example](https://github.com/ignitionrobotics/docs/pull/175))

* `ign-physics6`: Depends on `ign-common`, `ign-math`, `sdformat`
    - [x] Source code of all downstream libraries ([example](https://github.com/ignitionrobotics/ign-transport/pull/149))
    - [x] Release repositories of all downstream libraries ([example](https://github.com/ignition-release/ign-fuel-tools7-release/pull/1))
    - [x] Use `main` branch on `gazebodistro` ([example](https://github.com/ignition-tooling/gazebodistro/pull/42))
    - [x] Build nightlies from the `main` branch ([example](https://github.com/ignition-tooling/release-tools/pull/437))
    - [x] Update gzdev to use nightlies on CI ([example](https://github.com/ignition-tooling/gzdev/pull/31))
    - [x] homebrew-simulation: create formula and update dependencies ([example](https://github.com/osrf/homebrew-simulation/pull/14230))
    - [x] docs (the collection’s page) ([example](https://github.com/ignitionrobotics/docs/pull/175))

~~If #554 and #567 go through, bumping math shouldn't force the bump of anything that wouldn't already be bumped.~~ #554 is in, and #567 was absorbed into this one.

Downstream libraries affected:

* `ign-fuel-tools`
* `ign-gazebo`
* `ign-gui`
* `ign-launch`
* `ign-msgs`
* `ign-rendering`
* `ign-sensors`
* `ign-transport`

**Comment by scpeters** [comment]
@mjcarroll needs to add a dependency to ignition-math7, so I've used `bump_dependency.bash` to create new formulae for the relevant packages in this ticket. I ran the script for one package at a time in reverse order and only created the `homebrew-simulation` pull requests:

~~~
./bump_dependency.bash garden 'ign-physics' '6' 574 fortress 
./bump_dependency.bash garden 'sdformat' '13' 574 fortress 
./bump_dependency.bash garden 'ign-common' '5' 574 fortress 
./bump_dependency.bash garden 'ign-math' '7' 574 fortress 
~~~

these formulae have identical dependency information to the fortress versions, so the script will need to be run again to actually change the dependency versions

**Comment by chapulina** [comment]
Running `bash bump_dependency.bash garden "ign-math;ign-common;sdformat;ign-physics" "7;5;13;6" 574 fortress`
