### ISSUE TITLE
Use appveyor for some jobs

### ISSUE THREAD

**Issue by osrf-migration** [ignition-tooling/release-tools#59]
**Original report ([archived issue](https://osrf-migration.github.io/ignition-tooling-gh-pages/#!/osrf/release-tools/issues/59)) by Steve Peters (Bitbucket: [Steven Peters](https://bitbucket.org/%7B2ccfed09-18b8-4921-8d58-15ef01092802%7D/)).**

----------------------------------------
It would be nice to use appveyor for some of our packages. It is already enabled for ign-math but needs to be configured properly. Use dart as an example?

* https://github.com/dartsim/dart/blob/master/appveyor.yml

* https://ci.appveyor.com/project/scpeters/ign-math/build/1.0.302

**Comment by j-rivero** [comment]
already using different third party services in our repositories, from codecov to github actions or travis.
