### ISSUE TITLE
Repeat failed tests to identify flaky ones?

### ISSUE THREAD

**Issue by osrf-migration** [ignition-tooling/release-tools#60]
**Original report ([archived issue](https://osrf-migration.github.io/ignition-tooling-gh-pages/#!/osrf/release-tools/issues/60)) by Steve Peters (Bitbucket: [Steven Peters](https://bitbucket.org/%7B2ccfed09-18b8-4921-8d58-15ef01092802%7D/)).**

----------------------------------------
`ctest` has an option to repeat any failed tests (`--rerun-failed`). This could be used to identify flaky tests. It would take some work to manage the results files, since there would be duplicates of the repeated tests.

Perhaps it could work as follows:

1. Run `make test`, which will create junit files in the `test_results` folder.

2. Copy the `test_results` folder to `test_results_original`.

3. Run `make test ARGS="--rerun-failed"`, which will run the failed tests once more and over-write the junit files in `test_results`.

4. Repeat step 3 as desired.

Running this procedure should lead to a strictly decreasing number of test failures in `test_results`, since any tests that pass at least once will be shown as passing in the junit files in `test_results`. Any tests that failed in `test_results_original` but pass in `test_results` are flaky tests.

The Jenkins U/I would need a new element to display information about flaky tests, and we would also need some new logic to compare the results of `test_results_original` with `test_results`.

**Comment by j-rivero** [comment]
Implemented and running.
