### ISSUE TITLE
Aborting ignition-transport windows job can cause future jobs to fail

### ISSUE THREAD

**Issue by osrf-migration** [ignition-tooling/release-tools#62]
**Original report ([archived issue](https://osrf-migration.github.io/ignition-tooling-gh-pages/#!/osrf/release-tools/issues/62)) by Steve Peters (Bitbucket: [Steven Peters](https://bitbucket.org/%7B2ccfed09-18b8-4921-8d58-15ef01092802%7D/)).**

----------------------------------------
Logging in to the build machine and deleting the workspace folder fixed it, but we should make the build script more resilient to these types of situations.

@chapulina and I did this debugging together.

**Comment by scpeters** [comment]
this hasn't been a problem for a while
