### ISSUE TITLE
Mix of packages built with gcc-8 and gcc-9 lead to crashes when using std::filesystem

### ISSUE THREAD

**Issue by j-rivero** [ignition-tooling/release-tools#639]
@nkoenig and other have been reported problems on the destruction of `std::filesystem::path` https://github.com/ignitionrobotics/ign-gazebo/pull/1310#issuecomment-1032897809. The possible root cause is explained in https://stackoverflow.com/questions/63902528/program-crashes-when-filesystempath-is-destroyed and comes from the fact of building some ***binary packages with gcc-8 and others with gcc-9 and both software pieces using `std::filesystem`***.

Bionic has gcc-7 so the trick for using gcc-8 should be fine there. Focal is affected. Debian Buster is gcc-8, so I don't expect problems there. As far as I can see the only affected platform is Focal.

Looking into the code the only software using the `NEED_C17_COMPILER=true` should be transport7 and ignition-gazebo all versions. Some manual checks:

Packages (using std::filesystem) affected:
* ignition-common in nightlies on Focal (after https://github.com/ignitionrobotics/ign-common/pull/238)
* [ignition-gazebo6 stable on Focal](https://build.osrfoundation.org/job/ign-gazebo6-debbuilder/505/consoleFull#console-section-7) (built with gcc-8)
* [ignition-gazebo7 nightlies on Focal](https://build.osrfoundation.org/job/ign-gazebo7-debbuilder/194/consoleFull#console-section-7)

Packages not affected.
* ignition-math6 on Focal (built with gcc-9)
* ignition-utils on Focal (built with gcc-9)
 * [sdformat12 stable on Focal](https://build.osrfoundation.org/job/sdformat12-debbuilder/542/consoleFull#console-section-7). Built with gcc-9 but no std::filesystem.
* ignition-transport11 on Focal
* ignition-rendering6 on Focal
* ignition-sensors6 on Focal

**Comment by scpeters** [comment]
for whatever reason, ign-gazebo6 is using std::filesystem in https://github.com/ignitionrobotics/ign-gazebo/blob/ign-gazebo6/src/Util.cc#L21

**Comment by arjo129** [comment]
Seems like we are using it to check if a path is relative: https://github.com/ignitionrobotics/ign-gazebo/blob/faaa3ec2c9006db0be71be318e7f00be51d2a8e3/src/Util.cc#L365 . Would using the check we use for Apple help in this case? Seems like the Apple platform doesn't need `std::filesystem`.

**Comment by j-rivero** [comment]
Thanks @arjo129 for removing the use of std::filesystem in utils.cc. I think we are done here after latest releases using the right version of compiler. Please reopen if needed.
