### ISSUE TITLE
EOL collection: Edifice

### ISSUE THREAD

**Issue by chapulina** [ignition-tooling/release-tools#655]
- [x] Write a post to https://community.gazebosim.org/ announcing to the community it has last X weeks for finishing their PRs.
    * https://community.gazebosim.org/t/edifice-approaching-end-of-life/1328 
- [x] Check library versions that can be EOL’d on the [versions table](https://github.com/ignitionrobotics/docs/blob/master/tools/versions.md)
    * Ignition Fuel Tools 6
    * Ignition Gazebo 5
    * Ignition GUI 5
    * Ignition Edifice 1
    * Ignition Launch 4
    * Ignition Messages 7
    * Ignition Physics 4
    * Ignition Rendering 5
    * Ignition Sensors 5
    * Ignition Transport 10
    * SDFormat 11
- [x] Make releases with outstanding changes in each library about to be EOL'ed
    * Fuel tools
        - [x] https://github.com/ignitionrobotics/ign-fuel-tools/pull/242
        - [x] https://github.com/ignitionrobotics/ign-fuel-tools/pull/243
    * Gazebo
        - [x] https://github.com/ignitionrobotics/ign-gazebo/pull/1408
        - [x] Merge PRs targeted at `ign-gazebo5`: https://github.com/ignitionrobotics/ign-gazebo/pulls?q=is%3Apr+is%3Aopen+label%3A%22%F0%9F%8F%A2+edifice%22
        - [x] https://github.com/ignitionrobotics/ign-gazebo/pull/1420
    * GUI
        - [x] https://github.com/ignitionrobotics/ign-gui/pull/377
        - [x] https://github.com/ignitionrobotics/ign-gui/pull/378
    * Edifice
        - [x] https://github.com/ignitionrobotics/ign-edifice/pull/11
     * Launch
        - [x] Done
     * Messages
        - [x] Done
     * Physics
        - [x] There are no changes that would require a release: https://github.com/ignitionrobotics/ign-physics/compare/ignition-physics4_4.3.0...ign-physics4
     * Rendering
        - [x] https://github.com/ignitionrobotics/ign-rendering/pull/594
     * Sensors
        - [x] https://github.com/ignitionrobotics/ign-sensors/pull/208
     * Transport
        - [x] https://github.com/ignitionrobotics/ign-transport/pull/301
     * SDFormat
        - [x] Done
- [x] Archive release repos in [ignition-release](https://github.com/ignition-release) for all libraries after the last release has been made
- [x] Update `release-tools` after all releases have been made ([example](https://github.com/ignition-tooling/release-tools/pull/369))
    * https://github.com/ignition-tooling/release-tools/pull/676
- [x] Deprecate homebrew bottles (don't disable them) ([example](https://github.com/osrf/homebrew-simulation/pull/1242))
    * https://github.com/osrf/homebrew-simulation/pull/1785
- [x] Remove badges from `homebrew-simulation` README ([example](https://github.com/osrf/homebrew-simulation/pull/1772))
    * https://github.com/osrf/homebrew-simulation/pull/1846
- [x] Remove from buildfarmer ([dashboard](https://github.com/osrf/buildfarmer/pull/140) / [report](https://github.com/osrf/buildfarmer/pull/146))
    * https://github.com/osrf/buildfarmer/pull/297
- [x] Remove from `pr-collection-labeler` ([example](https://github.com/ignition-tooling/pr-collection-labeler/pull/13))
    * https://github.com/ignition-tooling/pr-collection-labeler/pull/23
- [x] Remove from `ros_ign` ([example](https://github.com/ignitionrobotics/ros_ign/pull/199))
    * Wait for Galactic EOL
- [x] Sync latest binaries to packages.ros.org 
    * https://github.com/ros-infrastructure/reprepro-updater/pull/146
- [x] Remove from `ign-docker-env` in `gzdev` ([example](https://github.com/ignition-tooling/gzdev/pull/56))
- [x] Close "<collection> support" ticket after final releases ([example](https://github.com/ignition-tooling/release-tools/issues/297#issuecomment-1002232980))
    * https://github.com/ignition-tooling/release-tools/issues/421
- [x] Update docs after EOL is complete ([example](https://github.com/ignitionrobotics/docs/pull/124))
    * https://github.com/ignitionrobotics/docs/pull/236
- [x] Announce EOL on https://community.gazebosim.org/ ([example](https://community.gazebosim.org/t/ignition-blueprint-officially-end-of-life/764))
    * https://community.gazebosim.org/t/ignition-edifice-officially-end-of-life/1350

**Comment by osrf-triage** [comment]
This issue has been mentioned on **Gazebo Community**. There might be relevant details there:

https://community.gazebosim.org/t/edifice-approaching-end-of-life/1328/1

**Comment by traversaro** [comment]
Self-remainder @traversaro: remove build of Edifice-only release for conda-forge, see for reference the PRs linked in https://github.com/ignition-tooling/release-tools/issues/600 for Dome.
