### ISSUE TITLE
Bump gazebo docker image versions from release.py

### ISSUE THREAD

**Issue by osrf-migration** [ignition-tooling/release-tools#68]
**Original report ([archived issue](https://osrf-migration.github.io/ignition-tooling-gh-pages/#!/osrf/release-tools/issues/68)) by Steve Peters (Bitbucket: [Steven Peters](https://bitbucket.org/%7B2ccfed09-18b8-4921-8d58-15ef01092802%7D/)).**

----------------------------------------
Just like we update the homebrew fomulae when we release new packages ([pull request #125](https://osrf-migration.github.io/ignition-tooling-gh-pages/#!/osrf/release-tools/pull-requests/125)), we should update the package versions in the gazebo docker images as well. This could automate the following pull request:

* https://github.com/osrf/docker_images/pull/35

Note that the pull request should update the version tag in the platform.yaml files and then run some scripts to populate the Dockerfiles.

cc: @ruffsl

**Comment by j-rivero** [comment]
Implemented in docker_images repository.
