### ISSUE TITLE
Bumps in Garden: ign-cmake3, ign-utils2, ign-tools2, ign-plugin2

### ISSUE THREAD

**Issue by methylDragon** [ignition-tooling/release-tools#685]
These bumps are being done to prepare for the migration from `ign` to `gz`.

## Libraries being bumped
* `ign-cmake3`:
    - [ ] Source code of all downstream libraries ([example](https://github.com/ignitionrobotics/ign-transport/pull/149))
    - [x] Release repositories of all downstream libraries ([example](https://github.com/ignition-release/ign-fuel-tools7-release/pull/1))
    - [x] Use `main` branch on `gazebodistro` ([example](https://github.com/ignition-tooling/gazebodistro/pull/42))
    - [x] Build nightlies from the `main` branch ([example](https://github.com/ignition-tooling/release-tools/pull/437))
    - [x] homebrew-simulation: create formula and update dependencies ([example](https://github.com/osrf/homebrew-simulation/pull/14230))
    - [x] docs (the collection’s page) ([example](https://github.com/ignitionrobotics/docs/pull/175))

* `ign-utils2`:
    - [x] Source code of all downstream libraries ([example](https://github.com/ignitionrobotics/ign-transport/pull/149))
    - [x] Release repositories of all downstream libraries ([example](https://github.com/ignition-release/ign-fuel-tools7-release/pull/1))
    - [x] Use `main` branch on `gazebodistro` ([example](https://github.com/ignition-tooling/gazebodistro/pull/42))
    - [x] Build nightlies from the `main` branch ([example](https://github.com/ignition-tooling/release-tools/pull/437))
    - [x] homebrew-simulation: create formula and update dependencies ([example](https://github.com/osrf/homebrew-simulation/pull/14230))
    - [x] docs (the collection’s page) ([example](https://github.com/ignitionrobotics/docs/pull/175))

* `ign-tools2`:
    - [ ] Source code of all downstream libraries ([example](https://github.com/ignitionrobotics/ign-transport/pull/149))
    - [x] Release repositories of all downstream libraries ([example](https://github.com/ignition-release/ign-fuel-tools7-release/pull/1))
    - [x] Use `main` branch on `gazebodistro` ([example](https://github.com/ignition-tooling/gazebodistro/pull/42))
    - [x] Build nightlies from the `main` branch ([example](https://github.com/ignition-tooling/release-tools/pull/437))
    - [x] homebrew-simulation: create formula and update dependencies ([example](https://github.com/osrf/homebrew-simulation/pull/14230))
    - [x] docs (the collection’s page) ([example](https://github.com/ignitionrobotics/docs/pull/175))

* `ign-plugin2`:
    - [x] Source code of all downstream libraries ([example](https://github.com/ignitionrobotics/ign-transport/pull/149))
    - [x] Release repositories of all downstream libraries ([example](https://github.com/ignition-release/ign-fuel-tools7-release/pull/1))
    - [x] Use `main` branch on `gazebodistro` ([example](https://github.com/ignition-tooling/gazebodistro/pull/42))
    - [x] Build nightlies from the `main` branch ([example](https://github.com/ignition-tooling/release-tools/pull/437))
    - [x] homebrew-simulation: create formula and update dependencies ([example](https://github.com/osrf/homebrew-simulation/pull/14230))
    - [x] docs (the collection’s page) ([example](https://github.com/ignitionrobotics/docs/pull/175))

## Downstream Libraries Affected

- `ign-math`
- `ign-msgs`
- `ign-common`
- `sdformat`
- `ign-transport`
- `ign-rendering`
- `ign-sensors`
- `ign-physics`
- `ign-gui`
- `ign-fuel-tools`
- `ign-gazebo`
- `ign-launch`
- `gazebo` (Leaving this alone, since we're not going to touch classic)

### Strategy
- [x] Bump `ign-cmake3`, `ign-utils2`, and `ign-plugin2` as an isolated stack first
- [x] Bump `ign-plugin2` and `ign-utils2` for the entire stack
- [x] Bump `ign-cmake3` and `ign-tools2` for the entire stack

### Topological Order (with level groups):
Bump higher order libraries first.
Libraries with the same order can be bumped in the same batch of PRs.

This manual ordering is needed until https://github.com/ignition-tooling/release-tools/issues/585 is resolved.

**Additional note**: We will make an exception in the merging order to do `ign-cmake3`, `ign-utils2`, and `ign-plugin2` as a separate stack first. Since those are unlikely to affect anything else until their changes are propagated following lower level merges.

  **7**
  - [x] (7, `ign-cmake`)
  
  **6**
  - [x] (6, `ign-utils`)
  
  **5**
  - [x] (5, `ign-tools`)
  - [x] (5, `ign-math`)
  
  **4**
  - [x] (4, `ign-plugin`)
  - [x] (4, `ign-msgs`)
  - [x] (4, `ign-common`)
  
  **3**
  - [x] (3, `sdformat`)
  - [x] (3, `ign-transport`)
  - [x] (3, `ign-rendering`)
  
  **2**
  - [x] (2, `ign-sensors`)
  - [x] (2, `ign-physics`)
  - [x] (2, `ign-gui`)
  - [x] (2, `ign-fuel-tools`)
  
  **1**
  - [x] (1, `ign-gazebo`)
  
  **0**
  - [x] (0, `ign-launch`)
  - (0, `gazebo`)  # <-- Leave this alone

### Release Script Edge Cases
Any random edge cases for the release repo scripts encountered in this undertaking are recorded here: https://github.com/ignition-tooling/release-tools/issues/689

**Comment by scpeters** [comment]
I don't see a homebrew-simulation PR for sdformat

**Comment by methylDragon** [comment]
Weird, I'll manually start one

**Comment by scpeters** [comment]
I just restarted windows CI for math, common, rendering and gui. We'll need to restart the others as well

**Comment by scpeters** [comment]
> I just restarted windows CI for math, common, rendering and gui. We'll need to restart the others as well

this first one failed: https://build.osrfoundation.org/job/ign_math-pr-win/311/

we may have to wipe the job workspace before these will pass

**Comment by chapulina** [comment]
Done! 👏🏽
