### ISSUE TITLE
Deadlock with orchestration

### ISSUE THREAD

**Issue by osrf-migration** [ignition-tooling/release-tools#70]
**Original report ([archived issue](https://osrf-migration.github.io/ignition-tooling-gh-pages/#!/osrf/release-tools/issues/70)) by Steve Peters (Bitbucket: [Steven Peters](https://bitbucket.org/%7B2ccfed09-18b8-4921-8d58-15ef01092802%7D/)).**

----------------------------------------
Tonight there were 5 `gazebo-ci-pr_any` jobs that were part running on maria.local, mostly waiting for executors to come available to start the different jobs. It reached the nightly reboot time, though, which prevents new jobs from starting. This appeared to be a deadlock situation, in which it would wait for ever for those jobs to finish, but they would never do so. I took the liberty of doing a forced restart, which allowed things to proceed.

We should think if there's a way to eliminate this deadlock.

**Comment by j-rivero** [comment]
We are not using Jenkins pipelines since we migrate to github. This was a major problem using them that should be consider for future implementations.
