### ISSUE TITLE
Mark bottle builds unstable if possible

### ISSUE THREAD

**Issue by osrf-migration** [ignition-tooling/release-tools#82]
**Original report ([archived issue](https://osrf-migration.github.io/ignition-tooling-gh-pages/#!/osrf/release-tools/issues/82)) by Steve Peters (Bitbucket: [Steven Peters](https://bitbucket.org/%7B2ccfed09-18b8-4921-8d58-15ef01092802%7D/)).**

----------------------------------------
Sometimes bottles build successfully, but `brew test-bot` complains that downstream bottles are still broken (for example with this [simbody build](http://build.osrfoundation.org/view/os_homebrew/job/generic-release-homebrew_bottle_builder/84/console)). It would be nice if that job was marked as unstable and the bottle and json file were exposed as artifacts. The downstream jobs could be skipped, but it would at least be nice to download those bottles for manual upload.

**Comment by scpeters** [comment]
it's not easy to detect why `brew test-bot` has failed. won't fix
