### ISSUE TITLE
Add short delay before starting ci-pr_any jobs

### ISSUE THREAD

**Issue by osrf-migration** [ignition-tooling/release-tools#86]
**Original report ([archived issue](https://osrf-migration.github.io/ignition-tooling-gh-pages/#!/osrf/release-tools/issues/86)) by Steve Peters (Bitbucket: [Steven Peters](https://bitbucket.org/%7B2ccfed09-18b8-4921-8d58-15ef01092802%7D/)).**

----------------------------------------
We currently have a pattern of updating the Changelog with pull request number immediately after making a pull request. The bitbucket watch starts the jenkins jobs and updates the build status very quickly, so the pull requests don't show up on the main pull request screen.

For example:

* build status not visible on [main page](https://bitbucket.org/osrf/gazebo/pull-requests/2480/qt-render-events-default/diff)
* though it is visible on the [commits page](https://bitbucket.org/osrf/gazebo/pull-requests/2480/qt-render-events-default/commits)

If we had a delay of 30 seconds or a minute that would give time to update the changelog.

cc: @nkoenig

**Comment by scpeters** [comment]
we aren't updating changelogs in PR's anymore
